apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
  labels:
    app: react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: reactapplication
        image: reactapp  #docker images name
        imagePullPolicy: Never   # This policy resolve the Imagepull back error so we can run the pods locally
        ports:
        - containerPort: 3000
